export const sharedTools = [
  {
    id: 'public-map',
    title: 'Публичная карта',
    description: 'Основной просмотр карты провинций.',
    path: 'index.html',
    tags: ['карта', 'провинции'],
  },
  {
    id: 'public-map-alt',
    title: 'Публичная карта v2',
    description: 'Альтернативный UI публичной карты.',
    path: 'index_ui_alt.html',
    tags: ['карта', 'новый UI'],
  },
  {
    id: 'hexmap',
    title: 'Hexmap',
    description: 'Гекс-карта и слои просмотра.',
    path: 'hexmap/index.html',
    tags: ['гексы', 'слои'],
  },
  {
    id: 'wiki',
    title: 'Энциклопедия мира',
    description: 'Публичная wiki/энциклопедия проекта.',
    path: 'wiki/index.html',
    tags: ['wiki', 'лор'],
  },
  {
    id: 'orders-feed',
    title: 'Летопись мира',
    description: 'Публичная лента приказов и событий.',
    path: 'orders_feed_ui_alt.html',
    tags: ['приказы', 'летопись'],
  },
  {
    id: 'diplomacy-console',
    title: 'Дипломатия',
    description: 'Консоль дипломатических сообщений, договоров и предложений.',
    path: 'diplomacy_console.html',
    tags: ['дипломатия'],
  },
  {
    id: 'entity-cabinet',
    title: 'Кабинет сущности',
    description: 'Кабинет дома/города/игровой сущности.',
    path: 'entity_cabinet.html',
    tags: ['кабинет'],
  },
  {
    id: 'entity-cabinet-alt',
    title: 'Кабинет сущности v2',
    description: 'Альтернативный кабинет сущности.',
    path: 'entity_cabinet_ui_alt.html',
    tags: ['кабинет', 'новый UI'],
  },
  {
    id: 'player-admin',
    title: 'Карта игрока',
    description: 'Ограниченная карта/админка по player-token.',
    path: 'player_admin.html',
    tags: ['игрок', 'token'],
  },
  {
    id: 'player-admin-alt',
    title: 'Карта игрока v2',
    description: 'Альтернативный UI player-admin.',
    path: 'player_admin_ui_alt.html',
    tags: ['игрок', 'token', 'новый UI'],
  },
  {
    id: 'player-orders',
    title: 'Приказы игрока',
    description: 'Кабинет подачи и просмотра приказов игрока.',
    path: 'player_orders_ui_alt.html',
    tags: ['приказы', 'игрок'],
  },
  {
    id: 'battle-session',
    title: 'Боевая сессия',
    description: 'Token battle session для игроков.',
    path: 'battle_sim/token.html',
    tags: ['битвы', 'token'],
  },
  {
    id: 'battle-token-entry',
    title: 'Вход в бой по токену',
    description: 'Точка входа token battle simulator.',
    path: 'battle_sim/token_sim.html',
    tags: ['битвы', 'token'],
  },
  {
    id: 'coa-editor',
    title: 'Генератор гербов',
    description: 'Публичный редактор SVG-гербов.',
    path: 'coa_editor/index.html',
    tags: ['гербы'],
  },
  {
    id: 'namegen',
    title: 'Генератор имён',
    description: 'Средневековый генератор имён.',
    path: 'namegen/index.html',
    tags: ['генераторы'],
  },
  {
    id: 'citygen',
    title: 'Генератор городов',
    description: 'Генератор city map.',
    path: 'citygen/index.html',
    tags: ['генераторы', 'города'],
  },
  {
    id: 'villagegen',
    title: 'Генератор деревень',
    description: 'Генератор village map.',
    path: 'villagegen/index.html',
    tags: ['генераторы', 'деревни'],
  },
  {
    id: 'genealogy-public',
    title: 'Генеалогия — публичная',
    description: 'Публичный просмотр genealogy simulator.',
    path: 'genealogy_simulator/index.html',
    tags: ['генеалогия'],
  },
  {
    id: 'micro-map',
    title: 'Микрокарта',
    description: 'Компактное представление карты.',
    path: 'micro.html',
    tags: ['карта'],
  },
];

export const tools = sharedTools;
export const clientConfig = {
  mode: 'user',
  defaultModule: 'public-map-alt',
};
