<?php
declare(strict_types=1);
require_once dirname(__DIR__, 3) . '/lib/orders_api.php';
$admin = orders_api_require_admin();
$id = trim((string)($_GET['id'] ?? ''));
$p = orders_api_request_payload();
if ($id === '') orders_api_response(['error'=>'id_required'],400);
orders_api_acquire_order_lock($id, $admin);
$store = orders_api_load_store();
$idx = orders_api_find_index($store['orders'], $id);
if ($idx < 0) orders_api_response(['error'=>'not_found'],404);
$order = $store['orders'][$idx];
orders_api_assert_version($order, $p, true);
$pub = orders_api_publish($order, $admin);
if (is_array($order['verdict'] ?? null)) $order['verdict']['published_at'] = gmdate('c');
$order['status'] = 'published';
$order['version'] = (int)$order['version'] + 1;
$order['updated_at'] = gmdate('c');
orders_api_audit_append($order,'order_published',$admin,['feed_id'=>$pub['id'] ?? '']);
$store['orders'][$idx] = $order;
orders_api_save_store($store);
orders_api_emit_order_etag($order);
$outboxRun = orders_api_process_outbox();
$outboxStatus = orders_api_outbox_status_for_order((string)$order['id']);
orders_api_response(['ok'=>true,'publication'=>$pub,'order'=>$order,'etag'=>orders_api_order_etag($order),'outbox_run'=>$outboxRun,'outbox_job_status'=>$outboxStatus]);
