export const sharedTools = [
  {
    id: 'public-map',
    title: 'Публичная карта',
    description: 'Основной просмотр карты провинций.',
    path: 'index.html',
    tags: ['карта', 'провинции'],
  },
  {
    id: 'public-map-alt',
    title: 'Публичная карта v2',
    description: 'Альтернативный UI публичной карты.',
    path: 'index_ui_alt.html',
    tags: ['карта', 'новый UI'],
  },
  {
    id: 'hexmap',
    title: 'Hexmap',
    description: 'Гекс-карта и слои просмотра.',
    path: 'hexmap/index.html',
    tags: ['гексы', 'слои'],
  },
  {
    id: 'wiki',
    title: 'Энциклопедия мира',
    description: 'Публичная wiki/энциклопедия проекта.',
    path: 'wiki/index.html',
    tags: ['wiki', 'лор'],
  },
  {
    id: 'orders-feed',
    title: 'Летопись мира',
    description: 'Публичная лента приказов и событий.',
    path: 'orders_feed_ui_alt.html',
    tags: ['приказы', 'летопись'],
  },
  {
    id: 'diplomacy-console',
    title: 'Дипломатия',
    description: 'Консоль дипломатических сообщений, договоров и предложений.',
    path: 'diplomacy_console.html',
    tags: ['дипломатия'],
  },
  {
    id: 'entity-cabinet',
    title: 'Кабинет сущности',
    description: 'Кабинет дома/города/игровой сущности.',
    path: 'entity_cabinet.html',
    tags: ['кабинет'],
  },
  {
    id: 'entity-cabinet-alt',
    title: 'Кабинет сущности v2',
    description: 'Альтернативный кабинет сущности.',
    path: 'entity_cabinet_ui_alt.html',
    tags: ['кабинет', 'новый UI'],
  },
  {
    id: 'player-admin',
    title: 'Карта игрока',
    description: 'Ограниченная карта/админка по player-token.',
    path: 'player_admin.html',
    tags: ['игрок', 'token'],
  },
  {
    id: 'player-admin-alt',
    title: 'Карта игрока v2',
    description: 'Альтернативный UI player-admin.',
    path: 'player_admin_ui_alt.html',
    tags: ['игрок', 'token', 'новый UI'],
  },
  {
    id: 'player-orders',
    title: 'Приказы игрока',
    description: 'Кабинет подачи и просмотра приказов игрока.',
    path: 'player_orders_ui_alt.html',
    tags: ['приказы', 'игрок'],
  },
  {
    id: 'battle-session',
    title: 'Боевая сессия',
    description: 'Token battle session для игроков.',
    path: 'battle_sim/token.html',
    tags: ['битвы', 'token'],
  },
  {
    id: 'battle-token-entry',
    title: 'Вход в бой по токену',
    description: 'Точка входа token battle simulator.',
    path: 'battle_sim/token_sim.html',
    tags: ['битвы', 'token'],
  },
  {
    id: 'coa-editor',
    title: 'Генератор гербов',
    description: 'Публичный редактор SVG-гербов.',
    path: 'coa_editor/index.html',
    tags: ['гербы'],
  },
  {
    id: 'namegen',
    title: 'Генератор имён',
    description: 'Средневековый генератор имён.',
    path: 'namegen/index.html',
    tags: ['генераторы'],
  },
  {
    id: 'citygen',
    title: 'Генератор городов',
    description: 'Генератор city map.',
    path: 'citygen/index.html',
    tags: ['генераторы', 'города'],
  },
  {
    id: 'villagegen',
    title: 'Генератор деревень',
    description: 'Генератор village map.',
    path: 'villagegen/index.html',
    tags: ['генераторы', 'деревни'],
  },
  {
    id: 'genealogy-public',
    title: 'Генеалогия — публичная',
    description: 'Публичный просмотр genealogy simulator.',
    path: 'genealogy_simulator/index.html',
    tags: ['генеалогия'],
  },
  {
    id: 'micro-map',
    title: 'Микрокарта',
    description: 'Компактное представление карты.',
    path: 'micro.html',
    tags: ['карта'],
  },
];

export const adminTools = [
  {
    id: 'admin-map',
    title: 'Админка карты',
    description: 'Основной редактор карты провинций.',
    path: 'admin.html',
    tags: ['админ', 'карта'],
  },
  {
    id: 'admin-map-alt',
    title: 'Админка карты v2',
    description: 'Альтернативный UI администрирования карты.',
    path: 'admin_ui_alt.html',
    tags: ['админ', 'карта', 'новый UI'],
  },
  {
    id: 'admin-map-v4',
    title: 'Admin v4',
    description: 'Новый админский клиент карты.',
    path: 'admin_v2.html',
    tags: ['админ', 'карта'],
  },
  {
    id: 'turn-admin',
    title: 'Админка ходов',
    description: 'Создание, обработка, публикация и rollback ходов.',
    path: 'turn_admin.html',
    tags: ['ходы'],
  },
  {
    id: 'orders-admin',
    title: 'Вердикты приказов',
    description: 'Админская очередь приказов, вердикты и эффекты.',
    path: 'admin_orders_ui_alt.html',
    tags: ['приказы'],
  },
  {
    id: 'war-admin',
    title: 'Админка войны',
    description: 'Управление войнами и битвами.',
    path: 'war_admin.html',
    tags: ['война', 'битвы'],
  },
  {
    id: 'battle-sim',
    title: 'Симулятор битв',
    description: 'Полный turn-based battle simulator.',
    path: 'battle_sim/index.html',
    tags: ['битвы'],
  },
  {
    id: 'wiki-admin',
    title: 'Админка Wiki',
    description: 'Редактор энциклопедии.',
    path: 'wiki/admin.html',
    tags: ['wiki'],
  },
  {
    id: 'genealogy-admin',
    title: 'Генеалогия рода',
    description: 'Админка genealogy API.',
    path: 'genealogy_admin.html',
    tags: ['генеалогия'],
  },
  {
    id: 'genealogy-sim-admin',
    title: 'Genealogy Simulator Admin',
    description: 'Админка genealogy simulator.',
    path: 'genealogy_simulator/admin.html',
    tags: ['генеалогия'],
  },
  {
    id: 'sidecar-admin',
    title: 'Sidecar Control Center',
    description: 'Модули, pipelines, запуск и cleanup sidecar-задач.',
    path: 'sidecar_admin.html',
    tags: ['sidecar'],
  },
  {
    id: 'vk-admin',
    title: 'VK Bot Admin',
    description: 'Админка VK bot integrations.',
    path: 'vk_admin.html',
    tags: ['vk'],
  },
  {
    id: 'coa-admin',
    title: 'Админка фигур SVG',
    description: 'Администрирование библиотеки фигур гербов.',
    path: 'coa_editor/admin.html',
    tags: ['гербы'],
  },
  {
    id: 'marine-provinces',
    title: 'Marine Provinces',
    description: 'Sidecar-модуль морских провинций.',
    path: 'mods/marine_provinces/admin.html',
    tags: ['модули', 'море'],
  },
  {
    id: 'river-logistics',
    title: 'River Logistics',
    description: 'Sidecar-модуль речной логистики.',
    path: 'mods/river_logistics/admin.html',
    tags: ['модули', 'реки'],
  },
  {
    id: 'raster-logistics',
    title: 'Raster Logistics',
    description: 'Unified raster logistics overlay.',
    path: 'mods/raster_logistics/admin.html',
    tags: ['модули', 'логистика'],
  },
  {
    id: 'enterprise-overlay',
    title: 'Enterprise Overlay',
    description: 'Enterprise overlay sidecar module.',
    path: 'mods/enterprise_overlay/admin.html',
    tags: ['модули', 'предприятия'],
  },
];

export const tools = [...adminTools, ...sharedTools];
export const clientConfig = {
  mode: 'admin',
  defaultModule: 'admin-map-v4',
};
export const userToolIds = new Set(sharedTools.map((tool) => tool.id));
export const adminToolIds = new Set(tools.map((tool) => tool.id));
