<?php

declare(strict_types=1);

return [
    ['id' => "wood_raw", 'name' => "Древесина", 'unit' => "м³", 'tier' => "raw", 'base_price' => 8, 'demand' => 0.45, 'decay' => 0, 'rarity' => 0.05],
    ['id' => "fiber_raw", 'name' => "Прядильное волокно", 'unit' => "кг", 'tier' => "raw", 'base_price' => 6, 'demand' => 0.42, 'decay' => 0.01, 'rarity' => 0.08],
    ['id' => "hides_raw", 'name' => "Необработанные шкуры", 'unit' => "шт", 'tier' => "raw", 'base_price' => 10, 'demand' => 0.18, 'decay' => 0, 'rarity' => 0.1],
    ['id' => "rubber_raw", 'name' => "Сырьевой каучук", 'unit' => "кг", 'tier' => "raw", 'base_price' => 14, 'demand' => 0.2, 'decay' => 0, 'rarity' => 0.2],
    ['id' => "petrochem_raw", 'name' => "Нефтехимическое сырьё", 'unit' => "кг", 'tier' => "raw", 'base_price' => 18, 'demand' => 0.22, 'decay' => 0, 'rarity' => 0.25],
    ['id' => "stone", 'name' => "Камень", 'unit' => "т", 'tier' => "raw", 'base_price' => 30, 'demand' => 0.26, 'decay' => 0, 'rarity' => 0.2],
    ['id' => "iron_ore", 'name' => "Железная руда", 'unit' => "т", 'tier' => "raw", 'base_price' => 20, 'demand' => 0.28, 'decay' => 0, 'rarity' => 0.18],
    ['id' => "coke", 'name' => "Кокс", 'unit' => "т", 'tier' => "raw", 'base_price' => 16, 'demand' => 0.24, 'decay' => 0, 'rarity' => 0.15],
    ['id' => "meat", 'name' => "Мясо", 'unit' => "кг", 'tier' => "raw", 'base_price' => 10, 'demand' => 0.24, 'decay' => 0.03, 'rarity' => 0.1],
    ['id' => "gold", 'name' => "Золото", 'unit' => "г", 'tier' => "raw", 'base_price' => 70, 'demand' => 0.04, 'decay' => 0, 'rarity' => 0.9],
    ['id' => "silver", 'name' => "Серебро", 'unit' => "кг", 'tier' => "raw", 'base_price' => 25, 'demand' => 0.07, 'decay' => 0, 'rarity' => 0.75],
    ['id' => "copper", 'name' => "Медь", 'unit' => "т", 'tier' => "raw", 'base_price' => 2000, 'demand' => 0.24, 'decay' => 0, 'rarity' => 0.45],
    ['id' => "iron", 'name' => "Железо", 'unit' => "т", 'tier' => "raw", 'base_price' => 500, 'demand' => 0.24, 'decay' => 0, 'rarity' => 0.2],
    ['id' => "lead", 'name' => "Свинец", 'unit' => "т", 'tier' => "raw", 'base_price' => 250, 'demand' => 0.24, 'decay' => 0, 'rarity' => 0.35],
    ['id' => "tin", 'name' => "Олово", 'unit' => "т", 'tier' => "raw", 'base_price' => 300, 'demand' => 0.24, 'decay' => 0, 'rarity' => 0.4],
    ['id' => "villadium", 'name' => "Вилладиум", 'unit' => "г", 'tier' => "raw", 'base_price' => 50, 'demand' => 0.03, 'decay' => 0, 'rarity' => 0.98],
    ['id' => "mutabryukva", 'name' => "Мутабрюква", 'unit' => "кг", 'tier' => "raw", 'base_price' => 0.35, 'demand' => 1.1, 'decay' => 0.02, 'rarity' => 0.03],
    ['id' => "mutachicken", 'name' => "Мутакурицы", 'unit' => "шт", 'tier' => "raw", 'base_price' => 9, 'demand' => 0.3, 'decay' => 0.01, 'rarity' => 0.06],
    ['id' => "e_parts", 'name' => "Электронные компоненты", 'unit' => "наб.", 'tier' => "component", 'base_price' => 85, 'demand' => 0.1, 'decay' => 0, 'rarity' => 0.7],
    ['id' => "rolled_steel", 'name' => "Прокатная сталь", 'unit' => "лист", 'tier' => "component", 'base_price' => 70, 'demand' => 0.12, 'decay' => 0, 'rarity' => 0.35],
    ['id' => "precision_steel", 'name' => "Высокоточная сталь", 'unit' => "лист", 'tier' => "component", 'base_price' => 120, 'demand' => 0.12, 'decay' => 0, 'rarity' => 0.55],
    ['id' => "mcu_set", 'name' => "Микропроцессорный набор", 'unit' => "шт", 'tier' => "component", 'base_price' => 240, 'demand' => 0.12, 'decay' => 0, 'rarity' => 0.92],
    ['id' => "filter_substrate", 'name' => "Фильтрующий субстрат", 'unit' => "кг", 'tier' => "component", 'base_price' => 45, 'demand' => 0.12, 'decay' => 0, 'rarity' => 0.35],
    ['id' => "electrolyte_chems", 'name' => "Химикаты для электролита", 'unit' => "л", 'tier' => "component", 'base_price' => 55, 'demand' => 0.12, 'decay' => 0, 'rarity' => 0.4],
    ['id' => "distilled_water", 'name' => "Дистиллированная вода", 'unit' => "л", 'tier' => "component", 'base_price' => 12, 'demand' => 0.12, 'decay' => 0, 'rarity' => 0.1],
    ['id' => "engine_kit", 'name' => "Комплект движка", 'unit' => "шт", 'tier' => "component", 'base_price' => 260, 'demand' => 0.08, 'decay' => 0, 'rarity' => 0.55],
    ['id' => "life_core", 'name' => "Ядро жизнеобеспечения", 'unit' => "шт", 'tier' => "component", 'base_price' => 320, 'demand' => 0.12, 'decay' => 0, 'rarity' => 0.75],
    ['id' => "bread", 'name' => "Хлеб", 'unit' => "кг", 'tier' => "component", 'base_price' => 1, 'demand' => 0.85, 'decay' => 0.02, 'rarity' => 0.05],
    ['id' => "meat_cans", 'name' => "Мясные консервы", 'unit' => "кг", 'tier' => "component", 'base_price' => 20, 'demand' => 0.12, 'decay' => 0, 'rarity' => 0.08],
    ['id' => "steel", 'name' => "Сталь", 'unit' => "т", 'tier' => "component", 'base_price' => 1000, 'demand' => 0.1, 'decay' => 0, 'rarity' => 0.3],
    ['id' => "wood_processed", 'name' => "Обработанная древесина", 'unit' => "м³", 'tier' => "component", 'base_price' => 18, 'demand' => 0.28, 'decay' => 0, 'rarity' => 0.06],
    ['id' => "armotextile", 'name' => "Бронетекстиль", 'unit' => "рулон", 'tier' => "component", 'base_price' => 95, 'demand' => 0.12, 'decay' => 0, 'rarity' => 0.3],
    ['id' => "leather_reinforced", 'name' => "Усиленная кожа", 'unit' => "компл.", 'tier' => "component", 'base_price' => 80, 'demand' => 0.12, 'decay' => 0, 'rarity' => 0.2],
    ['id' => "rubber_industrial", 'name' => "Промышленная резина", 'unit' => "компл.", 'tier' => "component", 'base_price' => 75, 'demand' => 0.12, 'decay' => 0, 'rarity' => 0.25],
    ['id' => "poly_housings", 'name' => "Полимерные корпуса", 'unit' => "компл.", 'tier' => "component", 'base_price' => 68, 'demand' => 0.12, 'decay' => 0, 'rarity' => 0.22],
    ['id' => "steel_ingot", 'name' => "Стальной слиток", 'unit' => "шт", 'tier' => "component", 'base_price' => 58, 'demand' => 0.12, 'decay' => 0, 'rarity' => 0.3],
    ['id' => "villadium_alloy", 'name' => "Вилладиумный сплав", 'unit' => "шт", 'tier' => "component", 'base_price' => 420, 'demand' => 0.12, 'decay' => 0, 'rarity' => 0.92],
    ['id' => "forged_parts", 'name' => "Кованые детали", 'unit' => "компл.", 'tier' => "component", 'base_price' => 60, 'demand' => 0.12, 'decay' => 0, 'rarity' => 0.2],
    ['id' => "precision_blanks", 'name' => "Высокоточные заготовки", 'unit' => "компл.", 'tier' => "component", 'base_price' => 135, 'demand' => 0.12, 'decay' => 0, 'rarity' => 0.55],
    ['id' => "stamped_frames", 'name' => "Штампованные рамы", 'unit' => "компл.", 'tier' => "component", 'base_price' => 88, 'demand' => 0.12, 'decay' => 0, 'rarity' => 0.32],
    ['id' => "power_module", 'name' => "Силовой модуль", 'unit' => "шт", 'tier' => "component", 'base_price' => 210, 'demand' => 0.12, 'decay' => 0, 'rarity' => 0.7],
    ['id' => "basic_electronics", 'name' => "Комплект базовой электроники", 'unit' => "шт", 'tier' => "component", 'base_price' => 140, 'demand' => 0.12, 'decay' => 0, 'rarity' => 0.55],
    ['id' => "adv_controller", 'name' => "Контроллер продвинутой электроники", 'unit' => "шт", 'tier' => "component", 'base_price' => 290, 'demand' => 0.12, 'decay' => 0, 'rarity' => 0.85],
    ['id' => "villadium_filter_ind", 'name' => "Вилладиумный фильтр промышленный", 'unit' => "шт", 'tier' => "component", 'base_price' => 520, 'demand' => 0.12, 'decay' => 0, 'rarity' => 0.95],
    ['id' => "electrolyte_ind", 'name' => "Промышленный электролит", 'unit' => "л", 'tier' => "component", 'base_price' => 45, 'demand' => 0.12, 'decay' => 0, 'rarity' => 0.35],
    ['id' => "life_module", 'name' => "Модуль жизнеобеспечения", 'unit' => "шт", 'tier' => "component", 'base_price' => 680, 'demand' => 0.12, 'decay' => 0, 'rarity' => 0.95],
    ['id' => "motor_small", 'name' => "Малый электродвигатель", 'unit' => "шт", 'tier' => "component", 'base_price' => 100, 'demand' => 0.12, 'decay' => 0, 'rarity' => 0.6],
    ['id' => "motor_medium", 'name' => "Средний электродвигатель", 'unit' => "шт", 'tier' => "component", 'base_price' => 1500, 'demand' => 0.12, 'decay' => 0, 'rarity' => 0.72],
    ['id' => "motor_heavy", 'name' => "Тяжёлый электродвигатель", 'unit' => "шт", 'tier' => "component", 'base_price' => 2000, 'demand' => 0.12, 'decay' => 0, 'rarity' => 0.82],
    ['id' => "villadium_filter_personal", 'name' => "Вилладиумный фильтр личный", 'unit' => "шт", 'tier' => "component", 'base_price' => 2, 'demand' => 0.12, 'decay' => 0, 'rarity' => 0.8],
    ['id' => "villadium_life_system", 'name' => "Вилладиумная система жизнеобеспечения", 'unit' => "шт", 'tier' => "component", 'base_price' => 600, 'demand' => 0.12, 'decay' => 0, 'rarity' => 0.98],
    ['id' => "leather_tanned", 'name' => "Кожа выделанная", 'unit' => "м", 'tier' => "component", 'base_price' => 3, 'demand' => 0.12, 'decay' => 0, 'rarity' => 0.12],
    ['id' => "cloth_peasant", 'name' => "Ткань простецкая", 'unit' => "м", 'tier' => "component", 'base_price' => 0.2, 'demand' => 0.12, 'decay' => 0, 'rarity' => 0.1],
    ['id' => "cloth_city", 'name' => "Ткань городская", 'unit' => "м", 'tier' => "component", 'base_price' => 2, 'demand' => 0.12, 'decay' => 0, 'rarity' => 0.18],
    ['id' => "cloth_noble", 'name' => "Ткань дворянская", 'unit' => "м", 'tier' => "component", 'base_price' => 8, 'demand' => 0.12, 'decay' => 0, 'rarity' => 0.35],
    ['id' => "wheel_moto", 'name' => "Колесо для мототехники", 'unit' => "шт", 'tier' => "component", 'base_price' => 20, 'demand' => 0.12, 'decay' => 0, 'rarity' => 0.3],
    ['id' => "wheel_car", 'name' => "Колесо для легковой техники", 'unit' => "шт", 'tier' => "component", 'base_price' => 150, 'demand' => 0.12, 'decay' => 0, 'rarity' => 0.35],
    ['id' => "wheel_truck", 'name' => "Колесо для грузовой техники", 'unit' => "шт", 'tier' => "component", 'base_price' => 200, 'demand' => 0.12, 'decay' => 0, 'rarity' => 0.45],
    ['id' => "armor_militia", 'name' => "Броня ополчения", 'unit' => "шт", 'tier' => "product", 'base_price' => 10.3, 'demand' => 0.05, 'decay' => 0, 'rarity' => 0],
    ['id' => "armor_aux", 'name' => "Броня Ауксилии", 'unit' => "шт", 'tier' => "product", 'base_price' => 105, 'demand' => 0.05, 'decay' => 0, 'rarity' => 0],
    ['id' => "armor_preventor", 'name' => "Броня Превентора", 'unit' => "шт", 'tier' => "product", 'base_price' => 1620, 'demand' => 0.05, 'decay' => 0, 'rarity' => 0],
    ['id' => "rifle_ep", 'name' => "Электропневматическая винтовка", 'unit' => "шт", 'tier' => "product", 'base_price' => 11.1, 'demand' => 0.05, 'decay' => 0, 'rarity' => 0],
    ['id' => "rifle_gauss", 'name' => "Гаусс-винтовка", 'unit' => "шт", 'tier' => "product", 'base_price' => 2625, 'demand' => 0.05, 'decay' => 0, 'rarity' => 0],
    ['id' => "spear_e", 'name' => "Электрокопьё", 'unit' => "шт", 'tier' => "product", 'base_price' => 5.5, 'demand' => 0.05, 'decay' => 0, 'rarity' => 0],
    ['id' => "railgun", 'name' => "Рельсотрон", 'unit' => "шт", 'tier' => "product", 'base_price' => 3200, 'demand' => 0.05, 'decay' => 0, 'rarity' => 0],
    ['id' => "assault_gun", 'name' => "Штурмовое орудие", 'unit' => "шт", 'tier' => "product", 'base_price' => 5200, 'demand' => 0.05, 'decay' => 0, 'rarity' => 0],
    ['id' => "pistol_e", 'name' => "Электропистолет", 'unit' => "шт", 'tier' => "product", 'base_price' => 420, 'demand' => 0.05, 'decay' => 0, 'rarity' => 0],
    ['id' => "sword_tac", 'name' => "Тактический меч", 'unit' => "шт", 'tier' => "product", 'base_price' => 260, 'demand' => 0.05, 'decay' => 0, 'rarity' => 0],
    ['id' => "gasmask", 'name' => "Противогаз", 'unit' => "шт", 'tier' => "product", 'base_price' => 10, 'demand' => 0.05, 'decay' => 0, 'rarity' => 0],
    ['id' => "motorcycle", 'name' => "Лёгкий электробайк", 'unit' => "шт", 'tier' => "product", 'base_price' => 550, 'demand' => 0.05, 'decay' => 0, 'rarity' => 0],
    ['id' => "jeep_raider", 'name' => "Джип-рейдер", 'unit' => "шт", 'tier' => "product", 'base_price' => 10700, 'demand' => 0.05, 'decay' => 0, 'rarity' => 0],
    ['id' => "boat_river", 'name' => "Речной катер", 'unit' => "шт", 'tier' => "product", 'base_price' => 3400, 'demand' => 0.05, 'decay' => 0, 'rarity' => 0],
    ['id' => "batt_ind", 'name' => "Промышленные аккумуляторы", 'unit' => "шт", 'tier' => "product", 'base_price' => 520, 'demand' => 0.05, 'decay' => 0, 'rarity' => 0],
    ['id' => "clothes_peasant", 'name' => "Крестьянская одежда", 'unit' => "шт", 'tier' => "product", 'base_price' => 2, 'demand' => 0.05, 'decay' => 0, 'rarity' => 0],
    ['id' => "clothes_city", 'name' => "Городская одежда", 'unit' => "шт", 'tier' => "product", 'base_price' => 10, 'demand' => 0.05, 'decay' => 0, 'rarity' => 0],
    ['id' => "clothes_noble", 'name' => "Дворянская одежда", 'unit' => "шт", 'tier' => "product", 'base_price' => 50, 'demand' => 0.05, 'decay' => 0, 'rarity' => 0],
    ['id' => "dishes_set", 'name' => "Посуда (10 компл.)", 'unit' => "компл.", 'tier' => "product", 'base_price' => 1, 'demand' => 0.05, 'decay' => 0, 'rarity' => 0],
    ['id' => "agri_tools", 'name' => "Сельскохозяйственный инструмент", 'unit' => "компл.", 'tier' => "product", 'base_price' => 1, 'demand' => 0.05, 'decay' => 0, 'rarity' => 0],
    ['id' => "motoblock", 'name' => "Мотоблок", 'unit' => "шт", 'tier' => "product", 'base_price' => 200, 'demand' => 0.05, 'decay' => 0, 'rarity' => 0],
    ['id' => "tricycle_truck", 'name' => "Грузовой трицикл", 'unit' => "шт", 'tier' => "product", 'base_price' => 400, 'demand' => 0.05, 'decay' => 0, 'rarity' => 0],
    ['id' => "jeep_civil", 'name' => "Гражданский джип", 'unit' => "шт", 'tier' => "product", 'base_price' => 4000, 'demand' => 0.05, 'decay' => 0, 'rarity' => 0],
    ['id' => "truck_civil", 'name' => "Гражданский грузовик", 'unit' => "шт", 'tier' => "product", 'base_price' => 7000, 'demand' => 0.02, 'decay' => 0, 'rarity' => 0],
    ['id' => "barge_river", 'name' => "Речная баржа", 'unit' => "шт", 'tier' => "product", 'base_price' => 12000, 'demand' => 0.05, 'decay' => 0, 'rarity' => 0],
    ['id' => "fertilizer_mineral", 'name' => "Минеральные удобрения (100 кг)", 'unit' => "парт.", 'tier' => "product", 'base_price' => 20, 'demand' => 0.05, 'decay' => 0, 'rarity' => 0],
    ['id' => "air_purifier_home", 'name' => "Личный домашний очиститель воздуха", 'unit' => "шт", 'tier' => "product", 'base_price' => 800, 'demand' => 0.05, 'decay' => 0, 'rarity' => 0],
    ['id' => "field_cat", 'name' => "Полевой кот", 'unit' => "шт", 'tier' => "animal", 'base_price' => 2560, 'demand' => 0.01, 'decay' => 0, 'rarity' => 0.15],
];
