<?php
declare(strict_types=1);
require_once dirname(__DIR__, 3) . '/lib/orders_api.php';
$admin = orders_api_require_admin();
$id = trim((string)($_GET['id'] ?? ''));
$p = orders_api_request_payload();
if ($id === '') orders_api_response(['error'=>'id_required'],400);
$store = orders_api_load_store();
$idx = orders_api_find_index($store['orders'], $id);
if ($idx < 0) orders_api_response(['error'=>'not_found'],404);
$order = $store['orders'][$idx];
orders_api_assert_version($order, $p, true);
$applied = orders_api_apply_effects($order, $admin);
$order['status'] = 'approved';
$order['version'] = (int)$order['version'] + 1;
$order['updated_at'] = gmdate('c');
orders_api_audit_append($order,'effects_applied',$admin,['applied'=>$applied]);
$store['orders'][$idx] = $order;
orders_api_save_store($store);
orders_api_response(['ok'=>true,'applied_effect_ids'=>$applied,'order'=>$order]);
